name: Build MiceCam

on:
  push:
    branches: [ "main", "feat/*", "fix/*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install System Dependencies (macOS)
      run: |
        brew install pkg-config nasm autoconf automake libtool autoconf-archive ninja

    - name: Setup vcpkg caches
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgGitCommitId: 1e199d32ad53aab1defda61ce41c380302e3f95c
        vcpkgDirectory: ${{ github.workspace }}/vcpkg
        vcpkgJsonGlob: '**/vcpkg.json'

    - name: Configure CMake
      run: >
        cmake -S ${{ github.workspace }} -B ${{ github.workspace }}/build
        -G Ninja
        -DCMAKE_BUILD_TYPE=Release
        -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake

    - name: Build All Targets
      run: cmake --build ${{ github.workspace }}/build --config Release
